"""Demo seed data for the in-memory PPG manager."""
from __future__ import annotations

from typing import Dict, List

import streamlit as st


def init_demo_db() -> Dict[str, List[dict]]:
    """Return deterministic demo data representing a full PPG."""
    return {
        "ppgs": [
            {
                "id": "ppg1",
                "name": "PPG Piloto",
                "description": "Ambiente DEMO para validar relações entre cadastros.",
            }
        ],
        "people": [
            {"id": "u_coord", "ppg_id": "ppg1", "name": "Coordenação PPG", "role": "coordenador"},
            {
                "id": "u_or1",
                "ppg_id": "ppg1",
                "name": "Prof. A",
                "role": "orientador",
                "linhas_ids": ["l1", "l3"],
            },
            {
                "id": "u_or2",
                "ppg_id": "ppg1",
                "name": "Prof. B",
                "role": "orientador",
                "linhas_ids": ["l2", "l3"],
            },
            {
                "id": "u_m1",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 1",
                "role": "mestrando",
                "orientador_id": "u_or1",
                "line_id": "l1",
                "status": "em_curso",
            },
            {
                "id": "u_m2",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 2",
                "role": "mestrando",
                "orientador_id": "u_or1",
                "line_id": "l1",
                "status": "em_curso",
            },
            {
                "id": "u_m3",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 3",
                "role": "mestrando",
                "orientador_id": "u_or2",
                "line_id": "l2",
                "status": "em_curso",
            },
            {
                "id": "u_m4",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 4",
                "role": "mestrando",
                "orientador_id": "u_or1",
                "line_id": "l3",
                "status": "em_curso",
            },
        ],
        "research_lines": [
            {
                "id": "l1",
                "ppg_id": "ppg1",
                "name": "Linha A — Estratégia e Governança",
                "description": "Estratégia, desempenho e governança em organizações.",
            },
            {
                "id": "l2",
                "ppg_id": "ppg1",
                "name": "Linha B — Inovação e Transformação Digital",
                "description": "Adoção de tecnologia, transformação e resultados.",
            },
            {
                "id": "l3",
                "ppg_id": "ppg1",
                "name": "Linha C — Sustentabilidade e ESG",
                "description": "ESG, sustentabilidade, disclosure e implicações organizacionais.",
            },
        ],
        "projects": [
            {
                "id": "p1",
                "ppg_id": "ppg1",
                "name": "Projeto 1 — Gestão e Estratégia em Organizações Públicas",
                "description": "Governança, planejamento e desempenho institucional.",
                "status": "em_andamento",
                "line_id": "l1",
                "orientadores_ids": ["u_or1"],
                "mestrandos_ids": ["u_m1", "u_m2"],
            },
            {
                "id": "p2",
                "ppg_id": "ppg1",
                "name": "Projeto 2 — Inovação e Transformação Digital em Serviços",
                "description": "Adoção tecnológica, processos e resultados em serviços.",
                "status": "em_andamento",
                "line_id": "l2",
                "orientadores_ids": ["u_or2"],
                "mestrandos_ids": ["u_m3"],
            },
            {
                "id": "p3",
                "ppg_id": "ppg1",
                "name": "Projeto 3 — Sustentabilidade, ESG e Estratégia",
                "description": "Práticas, narrativas e desempenho socioambiental.",
                "status": "planejamento",
                "line_id": "l3",
                "orientadores_ids": ["u_or1", "u_or2"],
                "mestrandos_ids": ["u_m4"],
            },
        ],
        "dissertations": [
            {
                "id": "d1",
                "ppg_id": "ppg1",
                "title": "Dissertação 1 — Governança e desempenho em instituições públicas",
                "summary": "Estudo sobre mecanismos de governança e seus efeitos no desempenho.",
                "status": "em_andamento",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m1",
                "artigos_ids": ["a1"],
                "ptts_ids": ["t1"],
            },
            {
                "id": "d2",
                "ppg_id": "ppg1",
                "title": "Dissertação 2 — Transformação digital e produtividade em serviços",
                "summary": "Investigação sobre adoção de tecnologias e produtividade.",
                "status": "em_andamento",
                "year": 2025,
                "line_id": "l2",
                "project_id": "p2",
                "orientador_id": "u_or2",
                "mestrando_id": "u_m3",
                "artigos_ids": ["a3"],
                "ptts_ids": ["t3"],
            },
            {
                "id": "d3",
                "ppg_id": "ppg1",
                "title": "Dissertação 3 — ESG e decisões estratégicas em organizações",
                "summary": "Análise de como práticas ESG influenciam decisões estratégicas.",
                "status": "em_andamento",
                "year": 2025,
                "line_id": "l3",
                "project_id": "p3",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m4",
                "artigos_ids": ["a4"],
                "ptts_ids": [],
            },
        ],
        "articles": [
            {
                "id": "a1",
                "ppg_id": "ppg1",
                "title": "Artigo 1 — Mecanismos de governança e desempenho",
                "summary": "Discussão sobre mecanismos de governança e indicadores de desempenho.",
                "status": "submetido",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "dissertation_id": "d1",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m1",
                "autores_texto": "Mestrando(a) 1; Prof. A",
            },
            {
                "id": "a2",
                "ppg_id": "ppg1",
                "title": "Artigo 2 — Estratégia e eficiência em instituições",
                "summary": "Comparação de práticas estratégicas e eficiência operacional.",
                "status": "em_andamento",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "dissertation_id": None,
                "orientador_id": "u_or1",
                "mestrando_id": "u_m2",
                "autores_texto": "Mestrando(a) 2; Prof. A",
            },
            {
                "id": "a3",
                "ppg_id": "ppg1",
                "title": "Artigo 3 — Transformação digital e produtividade",
                "summary": "Efeitos de tecnologias digitais na produtividade em serviços.",
                "status": "aceito",
                "year": 2025,
                "line_id": "l2",
                "project_id": "p2",
                "dissertation_id": "d2",
                "orientador_id": "u_or2",
                "mestrando_id": "u_m3",
                "autores_texto": "Mestrando(a) 3; Prof. B",
            },
            {
                "id": "a4",
                "ppg_id": "ppg1",
                "title": "Artigo 4 — ESG e decisões estratégicas",
                "summary": "Relações entre indicadores ESG e decisões estratégicas.",
                "status": "publicado",
                "year": 2025,
                "line_id": "l3",
                "project_id": "p3",
                "dissertation_id": "d3",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m4",
                "autores_texto": "Mestrando(a) 4; Prof. A; Prof. B",
            },
        ],
        "ptts": [
            {
                "id": "t1",
                "ppg_id": "ppg1",
                "title": "PTT 1 — Dashboard de indicadores de governança",
                "summary": "Dashboard para acompanhamento de indicadores de governança.",
                "tipo_ptt": "Dashboard / sistema de indicadores",
                "status": "em_andamento",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "dissertation_id": "d1",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m1",
            },
            {
                "id": "t2",
                "ppg_id": "ppg1",
                "title": "PTT 2 — Modelo de diagnóstico de maturidade ESG",
                "summary": "Ferramenta para diagnóstico de maturidade ESG em organizações.",
                "tipo_ptt": "Modelo de gestão / ferramenta de decisão",
                "status": "planejamento",
                "year": 2025,
                "line_id": "l3",
                "project_id": "p3",
                "dissertation_id": None,
                "orientador_id": "u_or2",
                "mestrando_id": "u_m4",
            },
            {
                "id": "t3",
                "ppg_id": "ppg1",
                "title": "PTT 3 — Protocolo de implantação de melhorias digitais",
                "summary": "Protocolo de implantação de melhorias digitais em serviços.",
                "tipo_ptt": "Protocolo / processo / método",
                "status": "concluido",
                "year": 2025,
                "line_id": "l2",
                "project_id": "p2",
                "dissertation_id": "d2",
                "orientador_id": "u_or2",
                "mestrando_id": "u_m3",
            },
        ],
        "evaluation_forms": {
            "articles": {
                "id": "f_art_1",
                "name": "Ficha Artigos — Administração (DEMO)",
                "criteria": [
                    {
                        "id": "c_art_1",
                        "name": "Aderência à linha de pesquisa",
                        "weight": 2,
                        "response_type": "scale_1_5",
                    },
                    {
                        "id": "c_art_2",
                        "name": "Contribuição teórica/gerencial",
                        "weight": 3,
                        "response_type": "scale_1_5",
                    },
                    {
                        "id": "c_art_3",
                        "name": "Rigor metodológico",
                        "weight": 3,
                        "response_type": "scale_1_5",
                    },
                    {
                        "id": "c_art_4",
                        "name": "Potencial de impacto/relevância",
                        "weight": 2,
                        "response_type": "scale_1_5",
                    },
                    {"id": "c_art_5", "name": "Ética e transparência", "weight": 1, "response_type": "yes_no"},
                ],
            },
            "ptts": {
                "id": "f_ptt_1",
                "name": "Ficha PTT — Administração (DEMO)",
                "ptt_types": [
                    "Software / aplicativo",
                    "Protocolo / processo / método",
                    "Manual / guia / cartilha",
                    "Dashboard / sistema de indicadores",
                    "Modelo de gestão / ferramenta de decisão",
                    "Relatório técnico / diagnóstico organizacional",
                ],
                "criteria": [
                    {
                        "id": "c_ptt_1",
                        "name": "Aplicabilidade gerencial",
                        "weight": 2,
                        "response_type": "scale_1_5",
                    },
                    {
                        "id": "c_ptt_2",
                        "name": "Grau de inovação",
                        "weight": 2,
                        "response_type": "scale_1_5",
                    },
                    {
                        "id": "c_ptt_3",
                        "name": "Maturidade/validação",
                        "weight": 3,
                        "response_type": "scale_1_5",
                    },
                    {"id": "c_ptt_4", "name": "Impacto mensurável", "weight": 3, "response_type": "scale_1_5"},
                    {
                        "id": "c_ptt_5",
                        "name": "Documentação/transferibilidade",
                        "weight": 2,
                        "response_type": "scale_1_5",
                    },
                ],
            },
        },
        "evaluations": [
            {
                "id": "e_a1",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a1",
                "evaluator_id": "u_coord",
                "form_type": "articles",
                "scores": {"c_art_1": 4, "c_art_2": 4, "c_art_3": 3, "c_art_4": 4, "c_art_5": 1},
                "final_score": 3.78,
                "notes": "Boa aderência e contribuição.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_a2",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a2",
                "evaluator_id": "u_or1",
                "form_type": "articles",
                "scores": {"c_art_1": 4, "c_art_2": 3, "c_art_3": 3, "c_art_4": 3, "c_art_5": 1},
                "final_score": 3.33,
                "notes": "Metodologia em consolidação.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_a3",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a3",
                "evaluator_id": "u_coord",
                "form_type": "articles",
                "scores": {"c_art_1": 5, "c_art_2": 4, "c_art_3": 4, "c_art_4": 4, "c_art_5": 1},
                "final_score": 4.22,
                "notes": "Excelente aderência e rigor.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_a4",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a4",
                "evaluator_id": "u_or2",
                "form_type": "articles",
                "scores": {"c_art_1": 4, "c_art_2": 5, "c_art_3": 4, "c_art_4": 5, "c_art_5": 1},
                "final_score": 4.56,
                "notes": "Alto impacto e contribuição.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_t1",
                "ppg_id": "ppg1",
                "target_type": "ptt",
                "target_id": "t1",
                "evaluator_id": "u_coord",
                "form_type": "ptts",
                "scores": {"c_ptt_1": 4, "c_ptt_2": 3, "c_ptt_3": 3, "c_ptt_4": 4, "c_ptt_5": 3},
                "final_score": 3.50,
                "notes": "Bom potencial com validação parcial.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_t2",
                "ppg_id": "ppg1",
                "target_type": "ptt",
                "target_id": "t2",
                "evaluator_id": "u_or2",
                "form_type": "ptts",
                "scores": {"c_ptt_1": 4, "c_ptt_2": 4, "c_ptt_3": 2, "c_ptt_4": 4, "c_ptt_5": 3},
                "final_score": 3.25,
                "notes": "Precisa avançar em maturidade/validação.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_t3",
                "ppg_id": "ppg1",
                "target_type": "ptt",
                "target_id": "t3",
                "evaluator_id": "u_coord",
                "form_type": "ptts",
                "scores": {"c_ptt_1": 5, "c_ptt_2": 4, "c_ptt_3": 4, "c_ptt_4": 4, "c_ptt_5": 4},
                "final_score": 4.22,
                "notes": "Produto maduro e replicável.",
                "created_at": "2025-12-30",
            },
        ],
    }


def ensure_demo_db() -> None:
    """Ensure demo database and context exist in session state."""
    if "db" not in st.session_state:
        st.session_state["db"] = init_demo_db()
    if "ctx" not in st.session_state:
        st.session_state["ctx"] = {"ppg_id": "ppg1", "profile": "coordenador", "person_id": None}
    st.session_state["ppg_id"] = st.session_state["ctx"]["ppg_id"]
    st.session_state["role"] = st.session_state["ctx"]["profile"]


__all__ = ["init_demo_db", "ensure_demo_db"]
