"""Demo seed data for the in-memory PPG manager."""
from __future__ import annotations

from typing import Dict, List

import streamlit as st

CURRENT_QUADRENNIUM = "2025-2028"

def init_demo_db() -> Dict[str, List[dict]]:
    """Return deterministic demo data representing a full PPG."""
    return {
        "ppgs": [
            {
                "id": "ppg1",
                "name": "PPG Piloto",
                "description": "Ambiente DEMO para validar relacoes entre cadastros.",
                "area": "Administracao, Ciencias Contabeis e Turismo",
                "campus": "IFMG - Campus Formiga",
                "modality": "Mestrado Profissional",
                "mission": "Formar profissionais e pesquisadores com foco em impacto aplicado.",
                "vision": "Ser referencia regional em formacao e impacto no ciclo CAPES.",
                "quadriennium": CURRENT_QUADRENNIUM,
            }
        ],
        "people": [
            {"id": "u_coord", "ppg_id": "ppg1", "name": "Coordenação PPG", "role": "coordenador"},
            {
                "id": "u_or1",
                "ppg_id": "ppg1",
                "name": "Prof. A",
                "role": "orientador",
                "linhas_ids": ["l1", "l3"],
            },
            {
                "id": "u_or2",
                "ppg_id": "ppg1",
                "name": "Prof. B",
                "role": "orientador",
                "linhas_ids": ["l2", "l3"],
            },
            {
                "id": "u_m1",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 1",
                "role": "mestrando",
                "orientador_id": "u_or1",
                "line_id": "l1",
                "status": "em_execucao",
            },
            {
                "id": "u_m2",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 2",
                "role": "mestrando",
                "orientador_id": "u_or1",
                "line_id": "l1",
                "status": "em_execucao",
            },
            {
                "id": "u_m3",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 3",
                "role": "mestrando",
                "orientador_id": "u_or2",
                "line_id": "l2",
                "status": "em_execucao",
            },
            {
                "id": "u_m4",
                "ppg_id": "ppg1",
                "name": "Mestrando(a) 4",
                "role": "mestrando",
                "orientador_id": "u_or1",
                "line_id": "l3",
                "status": "em_execucao",
            },
        ],
        "research_lines": [
            {
                "id": "l1",
                "ppg_id": "ppg1",
                "name": "Linha A — Estratégia e Governança",
                "description": "Estratégia, desempenho e governança em organizações.",
            },
            {
                "id": "l2",
                "ppg_id": "ppg1",
                "name": "Linha B — Inovação e Transformação Digital",
                "description": "Adoção de tecnologia, transformação e resultados.",
            },
            {
                "id": "l3",
                "ppg_id": "ppg1",
                "name": "Linha C — Sustentabilidade e ESG",
                "description": "ESG, sustentabilidade, disclosure e implicações organizacionais.",
            },
        ],
        "projects": [
            {
                "id": "p1",
                "ppg_id": "ppg1",
                "name": "Projeto 1 — Gestão e Estratégia em Organizações Públicas",
                "description": "Governança, planejamento e desempenho institucional.",
                "status": "em_execucao",
                "line_id": "l1",
                "orientadores_ids": ["u_or1"],
                "mestrandos_ids": ["u_m1", "u_m2"],
            },
            {
                "id": "p2",
                "ppg_id": "ppg1",
                "name": "Projeto 2 — Inovação e Transformação Digital em Serviços",
                "description": "Adoção tecnológica, processos e resultados em serviços.",
                "status": "em_execucao",
                "line_id": "l2",
                "orientadores_ids": ["u_or2"],
                "mestrandos_ids": ["u_m3"],
            },
            {
                "id": "p3",
                "ppg_id": "ppg1",
                "name": "Projeto 3 — Sustentabilidade, ESG e Estratégia",
                "description": "Práticas, narrativas e desempenho socioambiental.",
                "status": "planejado",
                "line_id": "l3",
                "orientadores_ids": ["u_or1", "u_or2"],
                "mestrandos_ids": ["u_m4"],
            },
        ],
        "dissertations": [
            {
                "id": "d1",
                "ppg_id": "ppg1",
                "title": "Dissertação 1 — Governança e desempenho em instituições públicas",
                "summary": "Estudo sobre mecanismos de governança e seus efeitos no desempenho.",
                "status": "planejado",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m1",
                "artigos_ids": ["a1"],
                "ptts_ids": ["t1"],
            },
            {
                "id": "d2",
                "ppg_id": "ppg1",
                "title": "Dissertação 2 — Transformação digital e produtividade em serviços",
                "summary": "Investigação sobre adoção de tecnologias e produtividade.",
                "status": "em_execucao",
                "year": 2025,
                "line_id": "l2",
                "project_id": "p2",
                "orientador_id": "u_or2",
                "mestrando_id": "u_m3",
                "artigos_ids": ["a3"],
                "ptts_ids": ["t3"],
            },
            {
                "id": "d3",
                "ppg_id": "ppg1",
                "title": "Dissertação 3 — ESG e decisões estratégicas em organizações",
                "summary": "Análise de como práticas ESG influenciam decisões estratégicas.",
                "status": "em_execucao",
                "year": 2025,
                "line_id": "l3",
                "project_id": "p3",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m4",
                "artigos_ids": ["a4"],
                "ptts_ids": [],
            },
        ],
        "articles": [
            {
                "id": "a1",
                "ppg_id": "ppg1",
                "title": "Artigo 1 — Mecanismos de governança e desempenho",
                "summary": "Discussão sobre mecanismos de governança e indicadores de desempenho.",
                "status": "em_execucao",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "dissertation_id": "d1",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m1",
                "autores_texto": "Mestrando(a) 1; Prof. A",
            },
            {
                "id": "a2",
                "ppg_id": "ppg1",
                "title": "Artigo 2 — Estratégia e eficiência em instituições",
                "summary": "Comparação de práticas estratégicas e eficiência operacional.",
                "status": "em_execucao",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "dissertation_id": None,
                "orientador_id": "u_or1",
                "mestrando_id": "u_m2",
                "autores_texto": "Mestrando(a) 2; Prof. A",
            },
            {
                "id": "a3",
                "ppg_id": "ppg1",
                "title": "Artigo 3 — Transformação digital e produtividade",
                "summary": "Efeitos de tecnologias digitais na produtividade em serviços.",
                "status": "concluido",
                "year": 2025,
                "line_id": "l2",
                "project_id": "p2",
                "dissertation_id": "d2",
                "orientador_id": "u_or2",
                "mestrando_id": "u_m3",
                "autores_texto": "Mestrando(a) 3; Prof. B",
            },
            {
                "id": "a4",
                "ppg_id": "ppg1",
                "title": "Artigo 4 — ESG e decisões estratégicas",
                "summary": "Relações entre indicadores ESG e decisões estratégicas.",
                "status": "concluido",
                "year": 2025,
                "line_id": "l3",
                "project_id": "p3",
                "dissertation_id": "d3",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m4",
                "autores_texto": "Mestrando(a) 4; Prof. A; Prof. B",
            },
        ],
        "ptts": [
            {
                "id": "t1",
                "ppg_id": "ppg1",
                "title": "PTT 1 — Dashboard de indicadores de governança",
                "summary": "Dashboard para acompanhamento de indicadores de governança.",
                "tipo_ptt": "Dashboard / sistema de indicadores",
                "status": "em_execucao",
                "year": 2025,
                "line_id": "l1",
                "project_id": "p1",
                "dissertation_id": "d1",
                "orientador_id": "u_or1",
                "mestrando_id": "u_m1",
            },
            {
                "id": "t2",
                "ppg_id": "ppg1",
                "title": "PTT 2 — Modelo de diagnóstico de maturidade ESG",
                "summary": "Ferramenta para diagnóstico de maturidade ESG em organizações.",
                "tipo_ptt": "Modelo de gestão / ferramenta de decisão",
                "status": "planejado",
                "year": 2025,
                "line_id": "l3",
                "project_id": "p3",
                "dissertation_id": None,
                "orientador_id": "u_or2",
                "mestrando_id": "u_m4",
            },
            {
                "id": "t3",
                "ppg_id": "ppg1",
                "title": "PTT 3 — Protocolo de implantação de melhorias digitais",
                "summary": "Protocolo de implantação de melhorias digitais em serviços.",
                "tipo_ptt": "Protocolo / processo / método",
                "status": "concluido",
                "year": 2025,
                "line_id": "l2",
                "project_id": "p2",
                "dissertation_id": "d2",
                "orientador_id": "u_or2",
                "mestrando_id": "u_m3",
            },
        ],
        "planning_goals": [
            {
                "id": "goal1",
                "ppg_id": "ppg1",
                "strategic_objective": "Consolidar portfolio de evidencias de impacto do PPG.",
                "action": "Documentar casos com narrativa, metricas e validacao externa.",
                "indicator": "Quantidade de casos de impacto validados",
                "target": "2 casos ate o fim do quadrienio",
                "deadline": "2028-12-31",
                "responsible": "Coordenacao do PPG",
                "status": "em_andamento",
                "related_evidence_id": "ev1",
            },
            {
                "id": "goal2",
                "ppg_id": "ppg1",
                "strategic_objective": "Institucionalizar autoavaliacao continua.",
                "action": "Executar ciclo anual com devolutiva e plano de encaminhamento.",
                "indicator": "Numero de ciclos completos por ano",
                "target": "1 ciclo concluido por ano",
                "deadline": "2026-12-31",
                "responsible": "Comissao de Autoavaliacao",
                "status": "planejado",
                "related_evidence_id": "ev2",
            },
        ],
        "self_assessments": [
            {
                "id": "sa1",
                "ppg_id": "ppg1",
                "cycle_period": "2025",
                "instrument": "Formulario eletronico e reuniao ampliada",
                "participants": "Docentes, discentes e egressos",
                "assessed_dimensions": "Formacao discente, impacto e insercao social",
                "key_findings": "Boa aderencia tematica, necessidade de reforco em escrita academica.",
                "weaknesses": "Baixa sistematizacao do acompanhamento de egressos.",
                "referrals": "Criar oficina de escrita e rotina de monitoramento de egressos.",
                "referrals_status": "em_andamento",
                "related_evidence_ids": ["ev2"],
            }
        ],
        "alumni": [
            {
                "id": "al1",
                "ppg_id": "ppg1",
                "name": "Egresso(a) 1",
                "cohort_year": 2024,
                "dissertation_project_ptt_link": "Dissertacao d1 / Projeto p1 / PTT t1",
                "professional_activity": "Gestao de planejamento e indicadores",
                "sector": "Setor publico",
                "position_role": "Gerente de Planejamento",
                "progression": "Promocao para cargo de lideranca apos conclusao",
                "evidence_testimonials": "Depoimento institucional e relatorio de resultados",
                "perceived_ppg_contribution": "Aplicacao pratica de metodos de governanca e avaliacao.",
            },
            {
                "id": "al2",
                "ppg_id": "ppg1",
                "name": "Egresso(a) 2",
                "cohort_year": 2023,
                "dissertation_project_ptt_link": "Projeto p2 / artigo aplicado",
                "professional_activity": "Consultoria em transformacao digital",
                "sector": "Setor privado",
                "position_role": "Consultor(a)",
                "progression": "Ampliacao de carteira e lideranca de projetos",
                "evidence_testimonials": "Relatos de clientes e portfolio profissional",
                "perceived_ppg_contribution": "Estruturacao de solucoes com base em pesquisa aplicada.",
            },
        ],
        "impact_cases": [
            {
                "id": "impact1",
                "ppg_id": "ppg1",
                "case_title": "Dashboard de governanca adotado por orgao publico",
                "context_problem": "Ausencia de monitoramento continuo de metas e indicadores.",
                "ppg_contribution": "Desenvolvimento do dashboard e protocolo de analise.",
                "involved_people_ids": ["u_or1", "u_m1"],
                "external_partners": "Secretaria municipal e equipe tecnica",
                "generated_product_action": "Implantacao de sistema de indicadores de governanca",
                "transfer_mechanism": "Projeto aplicado, oficinas e reunioes tecnicas",
                "results": "Uso recorrente em reunioes gerenciais e tomada de decisao.",
                "evidence_ids": ["ev1"],
                "replication_potential": "Alto potencial de reaplicacao em outros orgaos publicos.",
                "status": "em_documentacao",
            }
        ],
        "evidence_items": [
            {
                "id": "ev1",
                "ppg_id": "ppg1",
                "title": "Ata de implantacao do dashboard",
                "evidence_type": "Documento institucional",
                "related_module": "Casos de Impacto",
                "description": "Registro formal da entrega e implantacao do produto tecnico.",
                "link_file_path": "https://exemplo.local/ata-dashboard",
                "date": "2025-12-30",
                "notes": "Documento validado pela organizacao parceira.",
                "status": "validado",
            },
            {
                "id": "ev2",
                "ppg_id": "ppg1",
                "title": "Sintese do ciclo de autoavaliacao 2025",
                "evidence_type": "Relatorio",
                "related_module": "Autoavaliacao",
                "description": "Consolidacao dos achados, fragilidades e encaminhamentos do ciclo.",
                "link_file_path": "https://exemplo.local/autoavaliacao-2025",
                "date": "2025-12-30",
                "notes": "Versao preliminar em revisao.",
                "status": "rascunho",
            },
        ],
        "evaluation_forms": {
            "dissertations": {
                "id": "f_dis_1",
                "name": "Modelo Dissertação — Administração (DEMO)",
                "kind": "dissertacao",
                "scale": {
                    "metric_name": "Qualidade",
                    "levels": [
                        {"label": "Insuficiente", "value": 1},
                        {"label": "Regular", "value": 2},
                        {"label": "Bom", "value": 3},
                        {"label": "Muito bom", "value": 4},
                        {"label": "Excelente", "value": 5},
                    ],
                },
                "criteria": [
                    {"id": "c_dis_1", "name": "Relevância do tema", "weight": 2, "response_type": "scale_custom"},
                    {"id": "c_dis_2", "name": "Rigor metodológico", "weight": 3, "response_type": "scale_custom"},
                    {"id": "c_dis_3", "name": "Contribuição científica", "weight": 3, "response_type": "scale_custom"},
                    {"id": "c_dis_4", "name": "Qualidade da redação", "weight": 2, "response_type": "scale_custom"},
                ],
            },
            "articles": {
                "id": "f_art_1",
                "name": "Modelo Artigo — Administração (DEMO)",
                "kind": "artigo",
                "scale": {
                    "metric_name": "Qualidade",
                    "levels": [
                        {"label": "Insuficiente", "value": 1},
                        {"label": "Regular", "value": 2},
                        {"label": "Bom", "value": 3},
                        {"label": "Muito bom", "value": 4},
                        {"label": "Excelente", "value": 5},
                    ],
                },
                "criteria": [
                    {"id": "c_art_1", "name": "Aderência à linha de pesquisa", "weight": 2, "response_type": "scale_custom"},
                    {"id": "c_art_2", "name": "Contribuição teórica/gerencial", "weight": 3, "response_type": "scale_custom"},
                    {"id": "c_art_3", "name": "Rigor metodológico", "weight": 3, "response_type": "scale_custom"},
                    {"id": "c_art_4", "name": "Potencial de impacto/relevância", "weight": 2, "response_type": "scale_custom"},
                    {"id": "c_art_5", "name": "Ética e transparência", "weight": 1, "response_type": "scale_custom"},
                ],
            },
            "ptts": {
                "id": "f_ptt_1",
                "name": "Modelo PTT — Administração (DEMO)",
                "kind": "ptt",
                "scale": {
                    "metric_name": "Qualidade",
                    "levels": [
                        {"label": "Insuficiente", "value": 1},
                        {"label": "Regular", "value": 2},
                        {"label": "Bom", "value": 3},
                        {"label": "Muito bom", "value": 4},
                        {"label": "Excelente", "value": 5},
                    ],
                },
                "ptt_types": [
                    "Software / aplicativo",
                    "Protocolo / processo / método",
                    "Manual / guia / cartilha",
                    "Dashboard / sistema de indicadores",
                    "Modelo de gestão / ferramenta de decisão",
                    "Relatório técnico / diagnóstico organizacional",
                ],
                "criteria": [
                    {"id": "c_ptt_1", "name": "Aplicabilidade gerencial", "weight": 2, "response_type": "scale_custom"},
                    {"id": "c_ptt_2", "name": "Grau de inovação", "weight": 2, "response_type": "scale_custom"},
                    {"id": "c_ptt_3", "name": "Maturidade/validação", "weight": 3, "response_type": "scale_custom"},
                    {"id": "c_ptt_4", "name": "Impacto mensurável", "weight": 3, "response_type": "scale_custom"},
                    {"id": "c_ptt_5", "name": "Documentação/transferibilidade", "weight": 2, "response_type": "scale_custom"},
                ],
            },
        },
        "evaluations": [
            {
                "id": "e_a1",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a1",
                "evaluator_id": "u_coord",
                "form_type": "articles",
                "scores": {"c_art_1": 4, "c_art_2": 4, "c_art_3": 3, "c_art_4": 4, "c_art_5": 1},
                "final_score": 3.78,
                "notes": "Boa aderência e contribuição.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_a2",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a2",
                "evaluator_id": "u_or1",
                "form_type": "articles",
                "scores": {"c_art_1": 4, "c_art_2": 3, "c_art_3": 3, "c_art_4": 3, "c_art_5": 1},
                "final_score": 3.33,
                "notes": "Metodologia em consolidação.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_a3",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a3",
                "evaluator_id": "u_coord",
                "form_type": "articles",
                "scores": {"c_art_1": 5, "c_art_2": 4, "c_art_3": 4, "c_art_4": 4, "c_art_5": 1},
                "final_score": 4.22,
                "notes": "Excelente aderência e rigor.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_a4",
                "ppg_id": "ppg1",
                "target_type": "article",
                "target_id": "a4",
                "evaluator_id": "u_or2",
                "form_type": "articles",
                "scores": {"c_art_1": 4, "c_art_2": 5, "c_art_3": 4, "c_art_4": 5, "c_art_5": 1},
                "final_score": 4.56,
                "notes": "Alto impacto e contribuição.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_t1",
                "ppg_id": "ppg1",
                "target_type": "ptt",
                "target_id": "t1",
                "evaluator_id": "u_coord",
                "form_type": "ptts",
                "scores": {"c_ptt_1": 4, "c_ptt_2": 3, "c_ptt_3": 3, "c_ptt_4": 4, "c_ptt_5": 3},
                "final_score": 3.50,
                "notes": "Bom potencial com validação parcial.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_t2",
                "ppg_id": "ppg1",
                "target_type": "ptt",
                "target_id": "t2",
                "evaluator_id": "u_or2",
                "form_type": "ptts",
                "scores": {"c_ptt_1": 4, "c_ptt_2": 4, "c_ptt_3": 2, "c_ptt_4": 4, "c_ptt_5": 3},
                "final_score": 3.25,
                "notes": "Precisa avançar em maturidade/validação.",
                "created_at": "2025-12-30",
            },
            {
                "id": "e_t3",
                "ppg_id": "ppg1",
                "target_type": "ptt",
                "target_id": "t3",
                "evaluator_id": "u_coord",
                "form_type": "ptts",
                "scores": {"c_ptt_1": 5, "c_ptt_2": 4, "c_ptt_3": 4, "c_ptt_4": 4, "c_ptt_5": 4},
                "final_score": 4.22,
                "notes": "Produto maduro e replicável.",
                "created_at": "2025-12-30",
            },
        ],
    }


def ensure_demo_db() -> None:
    """Ensure demo database and context exist in session state."""
    if "db" not in st.session_state:
        st.session_state["db"] = init_demo_db()
    if "ctx" not in st.session_state:
        st.session_state["ctx"] = {"ppg_id": "ppg1", "profile": "coordenador", "person_id": None}
    st.session_state["ppg_id"] = st.session_state["ctx"]["ppg_id"]
    st.session_state["role"] = st.session_state["ctx"]["profile"]


__all__ = ["init_demo_db", "ensure_demo_db"]
